# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170710_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='measurement',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
