# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
